### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by dioh** [iocanel/hg2jj#2]
Trying to `rust run` latest version I find

```
  --- stderr
  Using stack size: Ok(3145728)
  fatal error: '/usr/include/libavcodec/vaapi.h' file not found
  fatal error: '/usr/include/libavcodec/vaapi.h' file not found, err: true
  thread 'ffmpg-sys-build' panicked at 'Unable to generate bindings: ()', /home/danito/.cargo/registry/src/github.com-1ecc6299db9ec823/ffmpeg-sys-4.3.3/build.rs:1279:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any { .. }', /home/danito/.cargo/registry/src/github.com-1ecc6299db9ec823/ffmpeg-sys-4.3.3/build.rs:6

```

Using arch latest version. Any clues?

**Comment by iocanel** [comment]
I am on archlinux myself and a recent upgrade broke things for me too. I am not 100% sure which package I installed to fix that.

But here's some things from my history:

```
sudo pacman -S libavcodec
sudo pacman -U https://archive.org/download/archlinux_pkg_ffmpeg/    ffmpeg-2:4.4-4-x86_64.pkg.tar.zst
```

To avoid this kind of issues, I've created a docker image, you may want to try it out, or get some ideas about the packages that are required (by examining the Dockerfile, it's debian based but you'll get a hint).

**Comment by iocanel** [comment]
@dioh: The `docker.io/iocanel/hg2jj:latest` image is now automatically updates on each merge to master. It should be easy to run the app via docker (See [Run as docker container](https://github.com/iocanel/hg2jj#as-a-docker-container)).

An other option is to provide a Dockerfile with `archlinux/base` so that it's easier to check what needs to be installed on arch.
